name: focal_agent_employees
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  #Data:
  connectivity_plus: ^4.0.1

  #Domain:
  equatable: ^2.0.5
  dartz: ^0.10.1

  #Presentation-State:
  flutter_bloc: ^8.1.3

  #Dependency Injection:
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/employees.json